services:
  - type: web
    name: free-fire-liker-api
    env: node
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_VERSION
        value: 16.15.0
      - key: RENDER
        value: true
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: true
      - key: CHROME_PATH
        value: /usr/bin/chromium-browser
    plan: free
